<?xml version='1.0' encoding='UTF-8'?>
<definitions
        xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:tns="http://localhost/SoapService"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://localhost/SoapService" name="SoapService">
    <types/>
    <message name="sendImageHexString">
        <part name="imageHexString" type="xsd:string"/>
    </message>
    <message name="sendImageHexStringResponse"/>
    <portType name="Soap">
        <operation name="sendImageHexString">
            <input wsam:Action="http://localhost/SoapService/Soap/sendImageHexStringRequest"
                   message="tns:sendImageHexString"/>
            <output wsam:Action="http://localhost/SoapService/Soap/sendImageHexStringResponse"
                    message="tns:sendImageHexStringResponse"/>
        </operation>
    </portType>
    <binding name="SoapPortBinding" type="tns:Soap">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
        <operation name="sendImageHexString">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal" namespace="http://localhost/SoapService"/>
            </input>
            <output>
                <soap:body use="literal" namespace="http://localhost/SoapService"/>
            </output>
        </operation>
    </binding>
    <service name="SoapService">
        <port name="SoapPort" binding="tns:SoapPortBinding">
            <soap:address location="http://localhost:8080/soapserver/SoapService/"/>
        </port>
    </service>
</definitions>