package wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Soap", targetNamespace = "http://wsserver/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Soap {

    /**
     * 
     * @param data
     */
    @WebMethod
    @Action(input = "http://wsserver/Soap/sendDataRequest", output = "http://wsserver/Soap/sendDataResponse")
    public void sendData(@WebParam(name = "data", partName = "data") byte[] data);

}